[package]

name = "single_glyph_ffi"
version = "0.0.0"
authors = ["Coeuvre <coeuvre@gmail.com>"]

[[bin]]

name = "single_glyph_ffi"
path = "./single_glyph_ffi.rs"

[dependencies.freetype-rs]

path = "../../"

