language: rust
notifications:
    irc: "irc.mozilla.org#piston-internals"
os:
    - linux
    - osx
env:
    global:
        - secure: DMlDiGHNvu6BxizTXu5If0SHASHUHUgd9/tKurFD6MEka6OlBEACFIpjWO6cVaIC8AeLiy4LGaxI6I9YJEap0Qdx9HTySk2qqFNdyav7XOKMZqVKKvGgbmJAWyiow7zJq7R7ZXbvIHykQCWWlBsIZEPkKesH6X0Zhri1GWqVw00=
install:
    # SDL2
    - curl -O http://libsdl.org/release/SDL2-2.0.3.tar.gz
    - tar -xzvf SDL2-2.0.3.tar.gz
    - (cd SDL2-2.0.3 && ./configure && make && sudo make install)
script:
    - cargo build -v
    - cargo test -v
    - cargo doc -v
after_success:
    - cp -R target/doc doc
    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
    - rm -r doc
