[package]

name = "freetype-rs"
version = "0.0.1"
authors = ["Coeuvre <coeuvre@gmail.com>"]
keywords = ["freetype", "font", "glyph"]
description = "Bindings for FreeType font library"
license = "MIT"
readme = "README.md"
repository = "https://github.com/PistonDevelopers/freetype-rs.git"
homepage = "https://github.com/PistonDevelopers/freetype-rs"

[lib]

name = "freetype"
path = "src/lib.rs"

[dependencies.freetype-sys]

git = "https://github.com/PistonDevelopers/freetype-sys"

