[package]

name = "freetype-rs"
version = "0.0.6"
authors = ["Coeuvre <coeuvre@gmail.com>"]
keywords = ["freetype", "font", "glyph"]
description = "Bindings for FreeType font library"
license = "MIT"
readme = "README.md"
repository = "https://github.com/PistonDevelopers/freetype-rs.git"
homepage = "https://github.com/PistonDevelopers/freetype-rs"

[lib]

name = "freetype"
path = "src/lib.rs"

[dependencies.freetype-sys]
git = "https://github.com/PistonDevelopers/freetype-sys"
#version = "0.0.2"

[dependencies]
bitflags = "*"

###### used for font with piston examples ######
[dev-dependencies.pistoncore-event]
git = "https://github.com/pistondevelopers/event"

[dev-dependencies.piston2d-opengl_graphics]
git = "https://github.com/pistondevelopers/opengl_graphics"

[dev-dependencies.piston2d-graphics]
git = "https://github.com/pistondevelopers/graphics"

[dev-dependencies.pistoncore-sdl2_window]
git = "https://github.com/pistondevelopers/sdl2_window"

[dev-dependencies.shader_version]
git = "https://github.com/PistonDevelopers/shader_version"
#################################################
