[package]

name = "freetype-rs"
version = "0.0.6"
authors = ["Coeuvre <coeuvre@gmail.com>"]
keywords = ["freetype", "font", "glyph"]
description = "Bindings for FreeType font library"
license = "MIT"
readme = "README.md"
repository = "https://github.com/PistonDevelopers/freetype-rs.git"
homepage = "https://github.com/PistonDevelopers/freetype-rs"

[lib]

name = "freetype"
path = "src/lib.rs"

[dependencies.freetype-sys]
git = "https://github.com/PistonDevelopers/freetype-sys"
#version = "0.0.2"

[dependencies]
bitflags = "*"
libc = "*"

###### used for font with piston example ######
[dev-dependencies.piston]
git = "https://github.com/PistonDevelopers/piston"

[dev-dependencies.piston2d-opengl_graphics]
git = "https://github.com/PistonDevelopers/opengl_graphics"

[dev-dependencies.piston2d-graphics]
git = "https://github.com/PistonDevelopers/graphics"

[dev-dependencies.pistoncore-sdl2_window]
git = "https://github.com/PistonDevelopers/sdl2_window"
###############################################
